### ISSUE TITLE
Inconsistent missing values

### ISSUE THREAD

**Issue by SultanOrazbayev** [DerwenAI/pynock#4]
This is probably a minor issue related to round-trip consistency, but it seems that depending on which format is used to store the data, the missing values are encoded differently. Consider the following:

```python
from subprocess import run

from pandas import read_csv, read_parquet

test_csv_out = "_test.csv"

_ = run(
    [
        "python3",
        "cli.py",
        "load-rdf",
        "--file",
        "dat/tiny.ttl",
        "--save-csv",
        test_csv_out,
    ]
)

test_pqt_out = "_test.pqt"

_ = run(
    [
        "python3",
        "cli.py",
        "load-rdf",
        "--file",
        "dat/tiny.ttl",
        "--save-parq",
        test_pqt_out,
    ]
)


df_csv = read_csv(test_csv_out)
df_pqt = read_parquet(test_pqt_out)
print(df_csv["labels"])
print(df_pqt["labels"])
```

This prints:

```pytb
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: labels, dtype: float64
0        
1    None
2        
3        
4        
5        
Name: labels, dtype: object
```

So the CSV version has consistent `NaN` values, while the parquet version has blanks and `None`. Having consistent missing values might be useful for downstream operations.

**Comment by ceteri** [comment]
Here's a screenshot of item-to-item comparisons
![image](https://user-images.githubusercontent.com/57973/193878815-e91f9c36-18df-4523-a5cb-8902f580635a.png)

**Comment by ceteri** [comment]
Definitely, this gets even more complicated by how some of the popular data tools handle missing values:

- JSON on C++ uses `null` instead of `""`
- Pandas `csv` methods serialize as `NaN` where the Python code uses `None`
- PyArrow Parquet serializes a `""` or `None` the same as Python does

We need to be able to handle whatever input these libraries and frameworks throw at us :) However, at the same time we need the `pynock` library output to be consistent.

My hunch is we need to replace the use of `pandas` CSV handler in the `pynock` output.

Also, we need to wrap this edge case into an additional `pytest` unit test.

**Comment by ceteri** [comment]
FWIW, I'm leaning toward using the C++ JSON library convention of an explicit `null` to represent a missing value.

Pandas and Excel make other assumptions, although these can become confusing.

**Comment by SultanOrazbayev** [comment]
> My hunch is we need to replace the use of pandas CSV handler in the pynock output.

Not sure if this is a good idea, but given `pandas`' popularity, it might be better to actually use `pandas` as a common denominator, so this way we'd store the results with their `.to_parquet` method.

**Comment by ceteri** [comment]
LOL :) That's how we got into this situation!

Yes, the popularity of `pandas` is good, although it's become one of the sources of "less consistency" in data management. Also, their approach to reading/writing Parquet via `DataFrame` objects can impose substantial bottlenecks at scale.

Instead, we must focus on the C++ low-level support for Parquet read/write with very clear semantics about the schema required. Then use of Spark for ETL becomes more of a common denominator – certainly for data at scale – with one small but important nuance: where Spark jobs are using the RDD level of abstraction, not Spark SQL.

With that in place, we can use this library as a way to bridge into whatever Excel, `pandas`, SQL Server, SAP, Kafka, PyG, etc., might throw at us :)

**Comment by SultanOrazbayev** [comment]
Re-running the code in the original snippet now gives the following:

```pytb
parse rows ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   
parse rows ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
Name: labels, dtype: float64
0        
1    None
2    None
3    None
4    None
5        
6        
7        
8        
Name: labels, dtype: object
```

The good news is that compared to the earlier screenshot, the differences are only in the columns: `labels` and `props`.

[Screenshot 2022-10-06 at 13.05.01.pdf](https://github.com/DerwenAI/pynock/files/9722062/Screenshot.2022-10-06.at.13.05.01.pdf)

**Comment by ceteri** [comment]
This issue on `pandas` https://github.com/pandas-dev/pandas/issues/10205 discusses how `NaN` is used to denote a missing value for a string column. Some of the semantics for `pandas` leave much to be desired :)

**Comment by SultanOrazbayev** [comment]
Ok, got it, this is a pandas.read_csv issue for NA.

**Comment by ceteri** [comment]
A quick workaround for `pandas`, which is getting added to our `FORMAT.md` notes is:

1. When using `pandas` to read Parquet files in `NOCK` format, to avoid having `NaN` substituted automatically for empty strings, use the `use_nullable_dtypes = True` setting:

```
df_parq = pd.read_parquet(
    "dat/tiny.parq",
    use_nullable_dtypes = True,
)
```

2. Similarly, when using `pandas` to read CSV files in `NOCK` format, use the `DataFrame.fillna("")` filter:

```
df_csv = pd.read_csv(
    "dat/tiny.csv",
).fillna("")

**Comment by SultanOrazbayev** [comment]
The results are still not quite the same:

```python
from subprocess import run

from pandas import read_csv, read_parquet

test_csv_out = "_test.csv"

_ = run(
    [
        "python3",
        "cli.py",
        "load-rdf",
        "--file",
        "dat/tiny.ttl",
        "--save-csv",
        test_csv_out,
    ]
)

test_pqt_out = "_test.pqt"

_ = run(
    [
        "python3",
        "cli.py",
        "load-rdf",
        "--file",
        "dat/tiny.ttl",
        "--save-parq",
        test_pqt_out,
    ]
)


df_csv = read_csv(test_csv_out).fillna("")
df_pqt = read_parquet(test_pqt_out,  use_nullable_dtypes = True)
print(df_csv["labels"])
print(df_pqt["labels"])

# parse rows ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   
# parse rows ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   
# 0    
# 1    
# 2    
# 3    
# 4    
# 5    
# 6    
# 7    
# 8    
# Name: labels, dtype: object
# 0        
# 1    <NA>
# 2    <NA>
# 3    <NA>
# 4    <NA>
# 5        
# 6        
# 7        
# 8        
# Name: labels, dtype: string
```

So, the `<NA>` is still there in the dataframe obtained via `read_parquet(..., use_nullable_dtypes = True)`. I guess, if we are doing `.fillna("")`, we can apply it also to the parquet dataframe, though it feels a bit hacky. However, in terms of priorities this is likely not very high, so I'm happy to use `.fillna` workaround for now.

**Comment by SultanOrazbayev** [comment]
Also, as a small side note: `assert len(df_csv.compare(df_parq)) == 0` passes, so that `<NA>` is treated as an empty string for comparison purposes... not what I expected initially, but I guess it also makes sense.

**Comment by ceteri** [comment]
Yes, the `DataFrame.compare()` function considers it as an empty string, although adding a `fillna("")` to the `read_parquet()` call also resolves this. 

To view a comparison, the unit test will show this now with:
```
python3 -m pytest -rP tests/test_pandas.py
```

**Comment by ceteri** [comment]
Just read above, we reached the same conclusion :)  A bit hacky, but workable.
Reading the `pandas` docs, this seems like a part of their API which is WIP, due to Arrow/Parquet evolving fast still.
